apiVersion: v1
kind: Namespace
metadata:
  name: osins
  labels:
    teamname: ositeam

# ---
# apiVersion: v1
# kind: ResourceQuota
# metadata:
#   name: resourcequotademo
#   namespace: osins
# spec:
#   hard:
#     requests.cpu: "1"
#     requests.memory: "1Gi"
#     limits.cpu: "2"
#     limits.memory: "2Gi"
#     pods: "2"