apiVersion: v1
kind: Pod
metadata:
  name: javawebapppod
  namespace: osins
  labels:
    app: javaapp
spec:
  containers:
  - name: javaappcontainer
    image: varunthamishetti123/java-web-app:1
    ports:
    - containerPort: 8080
    resources:
      requests:
        cpu: "500m"
        memory: "250Mi"
      limits:
        cpu: "1"
        memory: "1Gi"