apiVersion: v1
kind: ReplicationController
metadata:
  name: replicationcontroller
  namespace: osins
spec:
  replicas: 2
  template:  #pod information
    metadata:
      name: javarcpod
      labels:
        app: javarc
    spec:
     containers:
     - name: javarccontainer
       image: varunthamishetti123/java-web-app:1
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rcservice
spec:
 type: NodePort
 selector:
   app: javarc
 ports:
 - port: 80
   targetPort: 8080