apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: javarc
  namespace: osins
spec:
 replicas: 2
 selector:
   matchLabels:
     app: varma
 template:
   metadata:
     name: mavenwebapppod
     labels:
       app: varma
   spec:
     containers:
     - name: mavenwebappcontainer
       image: dockerhandson/maven-web-app:2
       ports:
       - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: rcservice123
  namespace: osins
spec:
 type: NodePort
 selector:
   app: varma
 ports:
 - port: 80
   targetPort: 8080
    
